apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmanager-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskmanager-backend
  template:
    metadata:
      labels:
        app: taskmanager-backend
    spec:
      containers:
      - name: taskmanager-backend
        #image: localhost:5000/taskmanager-backend:v1.0.0
        image: 192.168.49.2:30165/taskmanager-backend:v1.0.0
        ports:
        - containerPort: 8081
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
